import { AppProvider } from "../components/AppContext";
import Header from "../components/header/header";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({ subsets: ["latin"], weight: ['400', '500', '700'] });

export const metadata = {
  title: "SKY FOODS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <main className="h-screen flex flex-col">
          <AppProvider>
            <Toaster />

            <Header />
            <div className="flex-1">
              {children}
            </div>

            <footer className="border-t p-8 text-center text-gray-600 mt-16">
              &copy; 2024 All rights reserved
            </footer>
          </AppProvider>
          {/* Session provider in app provider in  src/components/AppContext.js*/}
        </main>
        </body>
    </html>
  );
}
